package com.marinboy.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/** 기존 DB에도 요일별 영업 규칙 테이블과 기본 영업시간을 안전하게 추가합니다. */
@Component
public class BusinessHourSchemaMigration implements CommandLineRunner {
    private final JdbcTemplate jdbcTemplate;

    public BusinessHourSchemaMigration(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        if (!tableExists("MB_BUSINESS_HOUR")) {
            jdbcTemplate.execute("""
                    CREATE TABLE MB_BUSINESS_HOUR (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        DAY_OF_WEEK NUMBER(1) NOT NULL UNIQUE,
                        IS_OPEN NUMBER(1) DEFAULT 1 NOT NULL,
                        OPEN_TIME VARCHAR2(5 CHAR) DEFAULT '10:00' NOT NULL,
                        CLOSE_TIME VARCHAR2(5 CHAR) DEFAULT '19:00' NOT NULL,
                        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                        CONSTRAINT CK_MB_BUSINESS_DAY CHECK (DAY_OF_WEEK BETWEEN 1 AND 7),
                        CONSTRAINT CK_MB_BUSINESS_OPEN CHECK (IS_OPEN IN (0, 1))
                    )
                    """);
        }

        // 기존 고객 예약을 갑자기 막지 않도록 모든 요일을 현재 영업시간으로 처음 등록합니다.
        for (int dayOfWeek = 1; dayOfWeek <= 7; dayOfWeek++) {
            jdbcTemplate.update("""
                    INSERT INTO MB_BUSINESS_HOUR (DAY_OF_WEEK, IS_OPEN, OPEN_TIME, CLOSE_TIME)
                    SELECT ?, 1, '10:00', '19:00'
                    FROM DUAL
                    WHERE NOT EXISTS (
                        SELECT 1 FROM MB_BUSINESS_HOUR WHERE DAY_OF_WEEK = ?
                    )
                    """, dayOfWeek, dayOfWeek);
        }
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ?", Integer.class, tableName);
        return count != null && count > 0;
    }
}
