package com.marinboy.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/** 이전 DB도 서버 시작 시 다중 소셜 계정 구조로 한 번만 안전하게 전환합니다. */
@Component
public class SocialAccountSchemaMigration implements CommandLineRunner {
    private final JdbcTemplate jdbcTemplate;

    public SocialAccountSchemaMigration(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        if (!tableExists("MB_USER")) {
            throw new IllegalStateException("MB_USER 테이블이 없습니다. Oracle 초기화 SQL을 먼저 실행해 주세요.");
        }

        //1. 새 연결 테이블이 없으면 생성해 기존 GitHub 다운로드 DB도 바로 실행되게 합니다.
        if (!tableExists("MB_USER_SOCIAL_ACCOUNT")) {
            jdbcTemplate.execute("""
                    CREATE TABLE MB_USER_SOCIAL_ACCOUNT (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        USER_ID NUMBER NOT NULL,
                        PROVIDER VARCHAR2(30 CHAR) NOT NULL,
                        SOCIAL_ID VARCHAR2(160 CHAR) NOT NULL,
                        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                        CONSTRAINT FK_MB_USER_SOCIAL_USER
                            FOREIGN KEY (USER_ID) REFERENCES MB_USER (ID) ON DELETE CASCADE,
                        CONSTRAINT UQ_MB_USER_SOCIAL_PROVIDER UNIQUE (USER_ID, PROVIDER),
                        CONSTRAINT UQ_MB_USER_SOCIAL_ID UNIQUE (PROVIDER, SOCIAL_ID)
                    )
                    """);
        }

        //2. 구버전 컬럼이 남아 있을 때만 데이터를 복사한 뒤 중복 저장 구조를 제거합니다.
        if (columnExists("MB_USER", "SOCIAL_PROVIDER")) {
            jdbcTemplate.update("""
                    INSERT INTO MB_USER_SOCIAL_ACCOUNT (USER_ID, PROVIDER, SOCIAL_ID)
                    SELECT U.ID, U.SOCIAL_PROVIDER, U.SOCIAL_ID
                    FROM MB_USER U
                    WHERE U.SOCIAL_PROVIDER IS NOT NULL
                      AND U.SOCIAL_ID IS NOT NULL
                      AND NOT EXISTS (
                          SELECT 1
                          FROM MB_USER_SOCIAL_ACCOUNT A
                          WHERE A.PROVIDER = U.SOCIAL_PROVIDER
                            AND A.SOCIAL_ID = U.SOCIAL_ID
                      )
                    """);
            if (constraintExists("UQ_MB_USER_SOCIAL")) {
                jdbcTemplate.execute("ALTER TABLE MB_USER DROP CONSTRAINT UQ_MB_USER_SOCIAL");
            }
            jdbcTemplate.execute("ALTER TABLE MB_USER DROP (SOCIAL_PROVIDER, SOCIAL_ID)");
        }
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ?", Integer.class, tableName);
        return count != null && count > 0;
    }

    private boolean columnExists(String tableName, String columnName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = ? AND COLUMN_NAME = ?",
                Integer.class, tableName, columnName);
        return count != null && count > 0;
    }

    private boolean constraintExists(String constraintName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = ?",
                Integer.class, constraintName);
        return count != null && count > 0;
    }
}
