-- Past completed reservation used to verify customer history.
MERGE INTO MB_RESERVATION R
USING (
    SELECT 9001 AS ID, U.NAME, U.EMAIL, U.PHONE
    FROM MB_USER U
    WHERE U.ID = 2
) S
ON (R.ID = S.ID)
WHEN MATCHED THEN UPDATE SET
    R.SERVICE_ID = 1,
    R.CUSTOMER_ID = 2,
    R.CUSTOMER_NAME = S.NAME,
    R.CUSTOMER_EMAIL = S.EMAIL,
    R.CUSTOMER_PHONE = S.PHONE,
    R.RESERVATION_DATE_TIME = SYSTIMESTAMP - INTERVAL '30' DAY,
    R.STATUS = 'COMPLETED',
    R.MEMO = 'Customer history sample'
WHEN NOT MATCHED THEN INSERT (
    ID, SERVICE_ID, CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE,
    RESERVATION_DATE_TIME, NO_SHOW_POLICY_AGREED, STATUS, MEMO
) VALUES (
    9001, 1, 2, S.NAME, S.EMAIL, S.PHONE,
    SYSTIMESTAMP - INTERVAL '30' DAY, 1, 'COMPLETED', 'Customer history sample'
);
COMMIT;
