-- 기존 DB의 2030년 데모 예약을 발표 시점 기준 가까운 날짜로 재배치합니다.
UPDATE MB_RESERVATION SET RESERVATION_DATE_TIME = SYSTIMESTAMP + INTERVAL '1' DAY WHERE ID IN (1, 10);
UPDATE MB_RESERVATION SET RESERVATION_DATE_TIME = SYSTIMESTAMP + INTERVAL '2' DAY WHERE ID = 11;
UPDATE MB_RESERVATION SET RESERVATION_DATE_TIME = SYSTIMESTAMP - INTERVAL '2' DAY WHERE ID = 12;
UPDATE MB_RESERVATION SET RESERVATION_DATE_TIME = SYSTIMESTAMP + INTERVAL '3' DAY WHERE ID = 13;
UPDATE MB_RESERVATION SET RESERVATION_DATE_TIME = SYSTIMESTAMP + INTERVAL '4' DAY WHERE ID = 14;
COMMIT;
