
-- 프로젝트에서 사용하는 MB_ 테이블이 모두 생성되었는지 확인합니다.
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'MB_%'
ORDER BY TABLE_NAME;

-- 고객/관리자 역할이 같은 사용자 테이블에서 구분되는지 확인합니다.
SELECT ID, USERNAME, NAME, ROLE
FROM MB_USER
ORDER BY ID;

-- 메뉴와 이미지가 분리되어 저장되었는지 확인합니다.
SELECT S.ID, S.NAME, S.CATEGORY, I.IMAGE_TYPE, I.SORT_ORDER
FROM MB_SERVICE_ITEM S
LEFT JOIN MB_SERVICE_IMAGE I ON I.SERVICE_ID = S.ID
ORDER BY S.ID, I.IMAGE_TYPE DESC, I.SORT_ORDER;

-- 관리자별 알림과 예약 상세 정보가 정상적으로 연결되는지 확인합니다.
SELECT N.ID, N.ADMIN_ID, N.IS_READ, N.MESSAGE, R.RESERVATION_DATE_TIME
FROM MB_NOTIFICATION N
JOIN MB_RESERVATION R ON R.ID = N.RESERVATION_ID
ORDER BY N.CREATED_AT DESC;

-- 관리자와 모바일 푸시 토큰 연결 상태를 확인합니다.
SELECT D.ID, D.ADMIN_ID, D.PLATFORM, D.UPDATED_AT
FROM MB_DEVICE_TOKEN D
JOIN MB_USER U ON U.ID = D.ADMIN_ID AND U.ROLE = 'ADMIN'
ORDER BY D.UPDATED_AT DESC;
