
-- 프로젝트에서 사용하는 MB_ 테이블이 모두 생성되었는지 확인합니다.
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'MB_%'
ORDER BY TABLE_NAME;

-- 고객/관리자 역할이 같은 사용자 테이블에서 구분되는지 확인합니다.
SELECT ID, USERNAME, NAME, ROLE
FROM MB_USER
ORDER BY ID;

-- 한 사용자가 제공자별 소셜 계정을 여러 개 연결할 수 있는지 확인합니다.
SELECT A.USER_ID, U.USERNAME, A.PROVIDER
FROM MB_USER_SOCIAL_ACCOUNT A
JOIN MB_USER U ON U.ID = A.USER_ID
ORDER BY A.USER_ID, A.PROVIDER;

-- 메뉴와 이미지가 분리되어 저장되었는지 확인합니다.
SELECT S.ID, S.NAME, S.CATEGORY, I.IMAGE_TYPE, I.SORT_ORDER
FROM MB_SERVICE_ITEM S
LEFT JOIN MB_SERVICE_IMAGE I ON I.SERVICE_ID = S.ID
ORDER BY S.ID, I.IMAGE_TYPE DESC, I.SORT_ORDER;

-- 예약이 고객·시술과 정상적으로 연결되는지 확인합니다.
SELECT R.ID, U.USERNAME, S.NAME AS SERVICE_NAME, R.RESERVATION_DATE_TIME, R.STATUS
FROM MB_RESERVATION R
JOIN MB_USER U ON U.ID = R.CUSTOMER_ID
JOIN MB_SERVICE_ITEM S ON S.ID = R.SERVICE_ID
ORDER BY R.RESERVATION_DATE_TIME DESC;
