import { useEffect, useState } from 'react';
import { sessionFetch as api } from '../features/shared/api/sessionApi';

export default function Reservation() {
  const [services, setServices] = useState([]); const [user, setUser] = useState(null); const [slots, setSlots] = useState([]); const [done, setDone] = useState(false); const [message, setMessage] = useState('');
  const [serviceId, setServiceId] = useState(''); const [date, setDate] = useState('');
  useEffect(() => { const selectedId = new URLSearchParams(window.location.search).get('serviceId'); Promise.all([api('/api/services'), api('/api/auth/me')]).then(async ([menu, me]) => { const items = menu.ok ? await menu.json() : []; setServices(items); setServiceId(selectedId || String(items[0]?.id || '')); setUser(me.status === 200 ? await me.json() : null); }).catch(() => setMessage('시술 메뉴를 불러오지 못했습니다.')); }, []);
  const loadSlots = async (nextDate) => { setDate(nextDate); if (!serviceId || !nextDate) return setSlots([]); const response = await api(`/api/services/${serviceId}/available-slots?date=${nextDate}`); setSlots(response.ok ? (await response.json()).availableSlots || [] : []); };
  const submit = async (event) => { event.preventDefault(); if (!user) return setMessage('예약하려면 먼저 로그인해 주세요.'); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await api('/api/reservations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ serviceId: Number(serviceId), reservationDateTime: data.reservationDateTime, memo: data.memo || '', customerName: user.name, customerEmail: user.email, customerPhone: user.phone, noShowPolicyAgreed: true }) }); if (!response.ok) return setMessage('예약에 실패했습니다. 선택한 시간을 다시 확인해 주세요.'); setDone(true); };
  return <main className="simple-page"><a href="/">← 홈으로</a><h1>시술 예약</h1><p>원하는 시술과 날짜, 시간을 선택해 주세요.</p>{message && <p role="alert">{message}</p>}<form className="simple-form" onSubmit={submit}><label>시술 메뉴<select value={serviceId} onChange={(e) => { setServiceId(e.target.value); if (date) loadSlots(date); }} required>{services.map((service) => <option key={service.id} value={service.id}>{service.name} · {Number(service.price).toLocaleString()}원</option>)}</select></label><label>예약 날짜<input type="date" min={new Date().toISOString().slice(0, 10)} value={date} onChange={(e) => loadSlots(e.target.value)} required /></label><label>예약 시간<select name="reservationDateTime" required disabled={!slots.length}><option value="">시간 선택</option>{slots.map((slot) => <option key={slot} value={slot}>{new Date(slot).toLocaleString('ko-KR')}</option>)}</select></label><label>요청 사항<textarea name="memo" placeholder="원하는 스타일 또는 참고 사항" /></label><button disabled={!user || !slots.length}>예약 완료</button>{!user && <small>로그인 후 예약할 수 있습니다.</small>}</form>{done && <div className="dialog-backdrop"><section className="dialog notification-modal"><h2>예약이 완료되었습니다</h2><p>결제는 시술 당일 매장에서 진행해 주세요.</p><button onClick={() => { setDone(false); window.location.href = '/my-reservations'; }}>나의 예약 확인</button></section></div>}</main>;
}
