
-- 개발 DB를 다시 구성할 때 기존 MB_ 테이블을 안전하게 제거합니다.
-- 소셜 연결과 이전 알림 테이블은 고객·예약보다 먼저 제거해 외래키 충돌을 막습니다.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_USER_SOCIAL_ACCOUNT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_NOTIFICATION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- 예약은 고객과 시술을 모두 참조하므로 부모 도메인 테이블보다 먼저 제거합니다.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_RESERVATION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- 시술 이미지도 시술 항목을 참조하므로 시술 테이블보다 먼저 제거합니다.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_SERVICE_IMAGE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- 참조 관계가 해제된 뒤 운영 설정과 고객·시술 기본 테이블을 제거합니다.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_HOLIDAY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_BUSINESS_HOUR CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_SERVICE_ITEM CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MB_USER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
