
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'MB_%'
ORDER BY TABLE_NAME;

-- 고객/관리자 역할이 같은 사용자 테이블에서 구분되는지 확인합니다.
SELECT ID, USERNAME, NAME, ROLE
FROM MB_USER
ORDER BY ID;

-- 메뉴와 이미지가 분리되어 저장되었는지 확인합니다.
SELECT S.ID, S.NAME, S.CATEGORY, I.IMAGE_TYPE, I.SORT_ORDER
FROM MB_SERVICE_ITEM S
LEFT JOIN MB_SERVICE_IMAGE I ON I.SERVICE_ID = S.ID
ORDER BY S.ID, I.IMAGE_TYPE DESC, I.SORT_ORDER;
