-- '?' 문자로 손상된 기존 고객/관리자 이름을 한글 이름으로 복구합니다.
-- UNISTR를 사용해 SQLPlus 실행 환경과 무관하게 UTF-8 이름을 저장합니다.
UPDATE MB_USER
SET NAME = CASE USERNAME
    WHEN 'admin' THEN UNISTR('\C0B4\B871 \AD00\B9AC\C790')
    WHEN 'customer' THEN UNISTR('\ACE0\AC1D \C0AC\C6A9\C790')
    WHEN 'seoyeon' THEN UNISTR('\AE40\C11C\C5F0')
    ELSE UNISTR('\ACE0\AC1D \C0AC\C6A9\C790')
END,
UPDATED_AT = SYSTIMESTAMP
WHERE REGEXP_LIKE(NAME, '^\\?');

UPDATE MB_RESERVATION R
SET CUSTOMER_NAME = (
    SELECT U.NAME FROM MB_USER U WHERE U.ID = R.CUSTOMER_ID
)
WHERE REGEXP_LIKE(R.CUSTOMER_NAME, '^\\?')
  AND EXISTS (SELECT 1 FROM MB_USER U WHERE U.ID = R.CUSTOMER_ID);

COMMIT;
